# Site settings
title: Python Brasil 11
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  11ª Conferência Brasileira da Comunidade Python. Cinco dias de
  Tutoriais, palestras e sprints sobre a linguagem Python.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pythonbrasil.github.io/pythonbrasil11-site" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
